app = "prod-1"

[build]
builder = "paketobuildpacks/builder:base"
buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]

[build.args]
NODE_ENV = "production"
NODE_VERSION = "20"

[env]
BOT_ID = 1
LOG_SPEAK = false
SENTRY_ENVIRONMENT = "production"
