app = "prod-2"

[build]
builder = "paketobuildpacks/builder:base"
buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]

[build.args]
NODE_ENV = "production"

[env]
BOT_ID = 2
LOG_SPEAK = false
SENTRY_ENVIRONMENT = "production"
