on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

env:
    IMAGE_NAME: andipaetzold/tttt-discord

name: release-please

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  release-type: node
                  include-component-in-tag: false

            #
            # Do the following steps after a release was created
            #

            - uses: actions/checkout@v4
              if: ${{ steps.release.outputs.release_created }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
              with:
                  platforms: "arm64,arm"
              if: ${{ steps.release.outputs.release_created }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              if: ${{ steps.release.outputs.release_created }}
            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
              if: ${{ steps.release.outputs.release_created }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./Dockerfile
                  platforms: linux/amd64,linux/arm64/v8
                  push: true
                  tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ steps.release.outputs.major }},${{ env.IMAGE_NAME }}:${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }},${{ env.IMAGE_NAME }}:${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
              if: ${{ steps.release.outputs.release_created }}
